# Generated by Django 4.2.18 on 2025-01-31 05:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Может содержать символы латиницы, цифры, дефис, подчёркивание.', max_length=256, unique=True, verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'категорию меню',
                'verbose_name_plural': 'Категории меню',
                'ordering': ('title',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Может содержать символы латиницы, цифры, дефис, подчёркивание.', max_length=256, unique=True, verbose_name='Идентификатор')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='orders.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'Меню',
                'ordering': ('title',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DishOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='Кол-во')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.dish', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'блюда',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], help_text='Укажите номер стола.', unique=True, verbose_name='Номер стола')),
            ],
            options={
                'verbose_name': ('стол заказов',),
                'verbose_name_plural': 'Столы заказов',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'в ожидании'), ('ready', 'готово'), ('paid', 'оплачено')], default='accepted', max_length=16, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время заказа')),
                ('items', models.ManyToManyField(through='orders.DishOrder', to='orders.dish', verbose_name='Блюда')),
                ('table_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.table', verbose_name='Номер стола')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('status', 'table_number'),
                'default_related_name': 'orders',
            },
        ),
        migrations.AddField(
            model_name='dishorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_dishes', to='orders.order', verbose_name='Заказ'),
        ),
    ]
