# Generated by Django 4.2.18 on 2025-02-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_table_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'принят'), ('ready', 'готово'), ('paid', 'оплачено')], default='accepted', max_length=16, verbose_name='Статус заказа'),
        ),
    ]
